# Use base64 encoded value for aws_access_key_id and aws_secret_access_key
apiVersion: v1
kind: Secret
metadata:
  name: covid-secrets
  namespace: covid
type: Opaque
data:
  aws_access_key_id: <aws_access_key_id>
  aws_secret_access_key: <aws_secret_access_key>
---
apiVersion: v1
kind: Secret
metadata:
  name: citi-bike-secrets
  namespace: citi-bike
type: Opaque
data:
  aws_access_key_id: <aws_access_key_id>
  aws_secret_access_key: <aws_secret_access_key>
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: airflow-secrets
data:
  POSTGRES_PASSWORD: <postgres_password>