source_domain:
- bucket: data-mesh-poc-ENVIRONMENT-data-mesh-covid-domain
  product:
  - italy/
  - us/
  folder:
  - raw/
  - canonical/
  - error/
- bucket: data-mesh-poc-ENVIRONMENT-citi-bike-data-bucket
  product:
  - bike-data/
  folder:
  - raw/
  - canonical/
  - error/
non_source_domain:
- bucket: data-mesh-poc-ENVIRONMENT-athena-data-mesh-output-bucket
- bucket: data-mesh-poc-ENVIRONMENT-emr-data-mesh-logging-bucket
