source_domain:
- bucket: covid-domain
  product:
  - italy/
  - us/
  folder:
  - raw/
  - canonical/
  - error/
- bucket: citi-bike-domain
  product:
  - bike-data/
  folder:
  - raw/
  - canonical/
  - error/
non_source_domain:
- bucket: athena-data-mesh-output-bucket
- bucket: emr-data-mesh-logging-bucket
